### ISSUE TITLE
it's good but make terminal slow

### ISSUE THREAD

**Issue by movenight** [mobilemancer/windows-terminal-aurelia#1]
it's very good but make terminal slow,There will be delays in use.It was unbearable, so I switched back to a simple theme.
I still like this cyberpunk style. :)

**Comment by mobilemancer** [comment]
It's unfortunately due to the retro terminal effect.
Set "experimental.retroTerminalEffect": false and it will be faster, but not as cool 😢

**Comment by mobilemancer** [comment]
Closing as it's out of my hands ¯\_(ツ)_/¯

**Comment by Chaphasilor** [comment]
maybe a custom pixel shader would help improve performance? it's an experimental feature :)  
https://youtu.be/FC-gLkYWXLw?t=597
